version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  reviewers:
  - nwtgck
  assignees:
  - nwtgck
  ignore:
  - dependency-name: fp-ts
    versions:
    - 2.10.0
    - 2.10.1
    - 2.10.4
  - dependency-name: sass
    versions:
    - 1.32.11
  - dependency-name: vuetify
    versions:
    - 2.4.10
  - dependency-name: core-js
    versions:
    - 3.11.0
  - dependency-name: vue-cli-plugin-vuetify
    versions:
    - 2.1.1
    - 2.2.0
    - 2.2.1
    - 2.3.0
  - dependency-name: "@vue/cli-plugin-pwa"
    versions:
    - 4.5.12
  - dependency-name: "@vue/cli-plugin-unit-mocha"
    versions:
    - 4.5.12
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.12
  - dependency-name: "@vue/cli-plugin-typescript"
    versions:
    - 4.5.12
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.12
  - dependency-name: clipboard
    versions:
    - 2.0.7
  - dependency-name: chai
    versions:
    - 4.3.1
    - 4.3.2
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: "@fortawesome/fontawesome-svg-core"
    versions:
    - 1.2.34
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  reviewers:
  - nwtgck
  assignees:
  - nwtgck
