name: netlify

on:
  push:
  pull_request:
    types: [opened, synchronize]

permissions:
  statuses: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.1.1
        with:
          node-version: 12.x
      - run: npm ci
      - run: SITE_URL="https://piping-ui.org" npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './dist'
          production-branch: master
          # NOTE: "production-branch" has higher priory than "alias".
          alias: git-${{ github.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-pull-request-comment: false
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

      - name: Generate Netlify alias
        shell: bash
        run: ruby -e 'puts "::set-output name=netlify_alias::#{`git branch --show-current`.chomp.gsub(/[^a-zA-Z\d]/){"-"}.downcase}"'
        id: get_netlify_alias
      # For branch deploy
      - name: Deploy to Netlify (branch)
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './dist'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alias: ${{ steps.get_netlify_alias.outputs.netlify_alias }}
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-commit-status: false
          github-deployment-environment: 'branch'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
